# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

F_gkb <- function(data, U, H, F0, m, gam, n, k, p, mcn, vp) {
    .Call(`_fclust_F_gkb`, data, U, H, F0, m, gam, n, k, p, mcn, vp)
}

F_gkb_ent <- function(data, U, H, F0, gam, n, k, p, mcn, vp) {
    .Call(`_fclust_F_gkb_ent`, data, U, H, F0, gam, n, k, p, mcn, vp)
}

F_gk <- function(data, U, H, m, n, k, p, vp) {
    .Call(`_fclust_F_gk`, data, U, H, m, n, k, p, vp)
}

F_gk_ent <- function(data, U, H, n, k, p, vp) {
    .Call(`_fclust_F_gk_ent`, data, U, H, n, k, p, vp)
}

mainFKM <- function(data, m, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM`, data, m, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_U <- function(data, m, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_U`, data, m, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_ent <- function(data, ent, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_ent`, data, ent, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_ent_U <- function(data, ent, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_ent_U`, data, ent, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_noise <- function(data, m, delta, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_noise`, data, m, delta, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_noise_U <- function(data, m, delta, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_noise_U`, data, m, delta, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_pf <- function(data, b, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_pf`, data, b, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_pf_U <- function(data, b, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_pf_U`, data, b, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_ent_noise <- function(data, ent, delta, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_ent_noise`, data, ent, delta, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_ent_noise_U <- function(data, ent, delta, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_ent_noise_U`, data, ent, delta, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_pf_noise <- function(data, b, delta, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_pf_noise`, data, b, delta, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_pf_noise_U <- function(data, b, delta, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_pf_noise_U`, data, b, delta, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gkb <- function(data, m, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb`, data, m, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gkb_U <- function(data, m, gam, mcn, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_U`, data, m, gam, mcn, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gkb_ent <- function(data, ent, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_ent`, data, ent, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gkb_ent_U <- function(data, gam, mcn, ent, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_ent_U`, data, gam, mcn, ent, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gkb_noise <- function(data, m, delta, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_noise`, data, m, delta, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gkb_noise_U <- function(data, m, gam, mcn, delta, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_noise_U`, data, m, gam, mcn, delta, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gkb_ent_noise <- function(data, ent, delta, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_ent_noise`, data, ent, delta, gam, mcn, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gkb_ent_noise_U <- function(data, ent, delta, gam, mcn, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gkb_ent_noise_U`, data, ent, delta, gam, mcn, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gk <- function(data, m, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk`, data, m, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gk_U <- function(data, m, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_U`, data, m, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gk_ent <- function(data, ent, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_ent`, data, ent, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gk_ent_U <- function(data, ent, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_ent_U`, data, ent, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gk_noise <- function(data, m, delta, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_noise`, data, m, delta, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gk_noise_U <- function(data, m, delta, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_noise_U`, data, m, delta, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_gk_ent_noise <- function(data, ent, delta, vp, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_ent_noise`, data, ent, delta, vp, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_gk_ent_noise_U <- function(data, ent, delta, vp, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_gk_ent_noise_U`, data, ent, delta, vp, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_med <- function(data, m, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_med`, data, m, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_med_U <- function(data, m, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_med_U`, data, m, n, p, k, U, conv, maxit, index, alpha)
}

mainFKM_med_noise <- function(data, m, delta, n, p, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_med_noise`, data, m, delta, n, p, k, rs, conv, maxit, index, alpha)
}

mainFKM_med_noise_U <- function(data, m, delta, n, p, k, U, conv, maxit, index, alpha) {
    .Call(`_fclust_mainFKM_med_noise_U`, data, m, delta, n, p, k, U, conv, maxit, index, alpha)
}

mainnefrc <- function(D, m, n, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainnefrc`, D, m, n, k, rs, conv, maxit, index, alpha)
}

mainnefrc_U <- function(D, U, m, n, k, conv, maxit, index, alpha) {
    .Call(`_fclust_mainnefrc_U`, D, U, m, n, k, conv, maxit, index, alpha)
}

mainrnefrc <- function(D, m, delta, n, k, rs, conv, maxit, index, alpha) {
    .Call(`_fclust_mainrnefrc`, D, m, delta, n, k, rs, conv, maxit, index, alpha)
}

mainrnefrc_U <- function(D, U, m, delta, n, k, conv, maxit, index, alpha) {
    .Call(`_fclust_mainrnefrc_U`, D, U, m, delta, n, k, conv, maxit, index, alpha)
}

centroids_FKM <- function(data, U, n, k, p, m) {
    .Call(`_fclust_centroids_FKM`, data, U, n, k, p, m)
}

centroids_FKM_ent <- function(data, U, n, k, p) {
    .Call(`_fclust_centroids_FKM_ent`, data, U, n, k, p)
}

centroids_FKM_pf <- function(data, U, n, k, p, b) {
    .Call(`_fclust_centroids_FKM_pf`, data, U, n, k, p, b)
}

medoids_FKM <- function(data, U, n, k, p, m) {
    .Call(`_fclust_medoids_FKM`, data, U, n, k, p, m)
}

euclidean_distance <- function(data, H, n, k, Square = FALSE) {
    .Call(`_fclust_euclidean_distance`, data, H, n, k, Square)
}

euclidean_distance_gkb <- function(data, H, F, n, k, Square = FALSE) {
    .Call(`_fclust_euclidean_distance_gkb`, data, H, F, n, k, Square)
}

euclidean_distance_gk <- function(data, H, F, D_old, n, k, p, Square = FALSE) {
    .Call(`_fclust_euclidean_distance_gk`, data, H, F, D_old, n, k, p, Square)
}

euclidean_distance_medoid <- function(data, H, n, k, Square = FALSE) {
    .Call(`_fclust_euclidean_distance_medoid`, data, H, n, k, Square)
}

replace <- function(x, val, change) {
    .Call(`_fclust_replace`, x, val, change)
}

InvCheck <- function(A) {
    .Call(`_fclust_InvCheck`, A)
}

Match <- function(i, B) {
    .Call(`_fclust_Match`, i, B)
}

distCheck <- function(D, n, p) {
    invisible(.Call(`_fclust_distCheck`, D, n, p))
}

silhouette_internal <- function(X, U, p, k, n, distance = FALSE) {
    .Call(`_fclust_silhouette_internal`, X, U, p, k, n, distance)
}

silhouette <- function(X, U, p, k, n, distance = FALSE) {
    .Call(`_fclust_silhouette`, X, U, p, k, n, distance)
}

silhouetteFuzzy <- function(X, U, alpha, p, k, n, distance = FALSE) {
    .Call(`_fclust_silhouetteFuzzy`, X, U, alpha, p, k, n, distance)
}

partCoef <- function(U, n) {
    .Call(`_fclust_partCoef`, U, n)
}

partEntropy <- function(U, b, n) {
    .Call(`_fclust_partEntropy`, U, b, n)
}

partCoef_mod <- function(U, n, k) {
    .Call(`_fclust_partCoef_mod`, U, n, k)
}

xie_beni <- function(X, U, H, m, n, k) {
    .Call(`_fclust_xie_beni`, X, U, H, m, n, k)
}

indices <- function(type, X, U, H, m, n, k, p, b, alpha, distance = FALSE) {
    .Call(`_fclust_indices`, type, X, U, H, m, n, k, p, b, alpha, distance)
}

unifInit <- function(n, d) {
    .Call(`_fclust_unifInit`, n, d)
}

memb_degree <- function(D, m, n, k, p) {
    .Call(`_fclust_memb_degree`, D, m, n, k, p)
}

memb_degree_pf <- function(D, b, n, k, p) {
    .Call(`_fclust_memb_degree_pf`, D, b, n, k, p)
}

memb_degree_ent <- function(D, ent, n, k, p) {
    .Call(`_fclust_memb_degree_ent`, D, ent, n, k, p)
}

memb_degree_medoid <- function(D, medoid, m, n, k, p) {
    .Call(`_fclust_memb_degree_medoid`, D, medoid, m, n, k, p)
}

partition_comp <- function(HardClust, Fuzzy, t_norm) {
    .Call(`_fclust_partition_comp`, HardClust, Fuzzy, t_norm)
}

